config/routes.rb
Rails.application.routes.draw do
  get 'bio_pic_pages/:id/edit', :to => 'bio_pic_pages#edit', :as => :edit_bio_pic_page

  get 'bio_pic_pages/:id/show', :to => 'bio_pic_pages#show', :as => :show_bio_pic_page

  post 'bio_pic_pages/:id/update', :to => 'bio_pic_pages#update', :as => :update_bio_pic_page

  post '/projects/create', :to => 'projects#create', :as => :project_create
  get '/projects', :to => 'projects#index', :as => :projects_index
  get '/projects/:id', :to => 'projects#show', :as => :project_show
  get '/skills', :to => 'skills#index', :as => :skills_index
  delete '/user-skills/:id/remove', :to => 'user_skills#destroy', :as => :remove_user_skill
  delete '/sessions', :to => 'sessions#destroy', :as => :destroy_session
  delete '/users/projects/:id/remove', :to => 'user_projects#remove', :as => :remove_user_project

  get 'skills/autocomplete_skill_name'

  get '/add-skill-field-form-row/:row_number', :to => 'bio_pic_pages#add_skill_field_form_row', :as => :add_skill_field_form_row

  post '/user-skills/:id/update', :to => 'user_skills#update', :as => :update_user_skill
  post '/search/results', :to => 'search#search_results', :as => :search_result
  root 'home#landing'

  resources :users
  resources :projects
  resources :skills do
    collection do
      get :show_by_category
    end
  end

  resources :categories

  get '/auth/google_oauth2/callback', as: "google_oauth", to: 'sessions#create'
end

app/controllers/bio_pic_pages_controller.rb
class BioPicPagesController < ApplicationController
  before_filter :authenticate
  before_filter :authorize, :only => [:edit, :update]

  before_action :set_user, :except => [:add_skill_field_form_row]

  def edit
  	@projects = Project.all_except(@user.projects)
    @autocomplete_items = Skill.pluck(:name)
  end

  def show

  	@user_mastered_skills = @user.skills.group_by{|skill| skill.user_skill(@user.id).mastered}[true]
  	@user_learning_skills = @user.skills.group_by{|skill| skill.user_skill(@user.id).mastered}[false]
  end
  
  def update
    @user.update_columns({:designation => params["bio_pic_pages"]["user"]["designation"], :education_qualification => params["bio_pic_pages"]["user"]["education_qualification"]})

  	skills = params[:bio_pic_pages][:user_skills]
    # has_many through
  	begin
      skills.each do |key, value|
        name = value["name"] == "no existing match" ? "" : value["name"]
        skill_db_object = Skill.find_by_name(name.try(:downcase))
        if !skill_db_object.present? && name.present?
          
          skill = Skill.create(name: name.downcase, :category_id => value["category_id"].to_i)
          @user.user_skills.create!(:skill_id => skill.id, :mastered => value["mastered"], :description => value["description"])
        elsif skill_db_object.present? && name.present? && UserSkill.find_by_skill_id_and_user_id(skill_db_object.id, current_user.id).nil?

          @user.user_skills.create!(:skill_id => skill_db_object.id, :mastered => value["mastered"], :description => value["description"])

        end
      end
      # HABTM  projects_users table
      if params[:bio_pic_pages].has_key?(:user_projects)
        selected_projects = Project.where(:id => [params[:bio_pic_pages][:user_projects]])
        selected_projects.each do |selected_project|
          @user.projects << selected_project if !@user.projects.include?(selected_project)
        end
      end

      flash[:message] = "Profile updated successfully"
      redirect_to show_bio_pic_page_path(@user.id), :notice => "User Bio Pic Page updated successfully."

    rescue ActiveRecord::RecordInvalid => e
      flash[:errors] = e.message
      redirect_to edit_bio_pic_page_path(@user.id)
    end
  end

  def add_skill_field_form_row
    @search_field_number = params[:row_number]
    respond_to do |format|
      format.js
    end
  end
 private
 def set_user
 	@user = User.eager_load(:skills => [:user_skills, :category]).where(:users => {:id => params[:id]}).first
 	
  redirect_to show_bio_pic_page_path(current_user.id), :notice => "Invalid User ID" if @user.nil?
 end

 def project_params
   params.require(:user).permit(:skills_attributes, :projects_attributes, :education_qualification, :designation)
 end

end

app/helpers/bio_pic_pages_helper.rb
module BioPicPagesHelper
end

app/views/bio_pic_pages/_form.html.erb
<style type="text/css">
  .form-horizontal .form-group {
    margin-left: 0px !important;
    margin-right: 0px !important;
  }
</style>
<div class="container">
  <%= flash[:message] %>
  <%= flash[:errors] %>
  <h4 style = "text-align: center; color:black; font-size: 48px;">Edit User Information</h4>
  <%= render :partial => 'projects/form_modal' %>
  <% @user.skills.each do |skill| %>
    <%= render :partial => 'skills/edit_user_skill_modal', :locals => {:user_skill_id => skill.user_skill(@user.id).id} %>
  <% end %>
  <%= form_tag(update_bio_pic_page_path(@user.id) , :class => "form-horizontal skill_form", :method => "post") do %>
    
    <div class="form-group">
      <div class="col-lg-12">
        <label>Educational Qualification</label>
        <%= text_field_tag 'bio_pic_pages[user][education_qualification]',@user.education_qualification, :class => "form-control" %>
      </div>
      <br />
      <br />
      <br />
      <div class="col-lg-12">
        <label>Designation</label>
        <%= text_field_tag 'bio_pic_pages[user][designation]',  @user.designation, :class => "form-control" %>
      </div>
      
    </div>
    
    <div class="form-group">
      <div class="col-lg-12">
        <h3>Skills </h3>
      </div>
    </div>

    <div class="col-lg-12">
      <% if ["edit", "update"].include?(params[:action]) && @user.skills.present? %>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th><b>Skill Name</b></th>
              <th><b>Category</b></th>
              <th><b>Learning Level</b></th>
              <th colspan="2"><b>Actions</b></th>
              </tr>
          </thead>

          <tbody>
            <% @user.skills.each do |skill| %>
              <tr id='<%= "user_skill_table_row_#{skill.user_skill(@user.id).id}" %>'>
                <td><%= skill.name.titleize %></td>
                <td><%= skill.category.name %></td>
                <td id="user_skill_<%= skill.user_skill(@user.id).id %>_learning_level"><%= skill.user_skill(@user.id).mastered? ? "Mastered" : "Learning" %></td>
                <td><%= link_to 'Update', '#', :id => "update_user_skill_#{skill.user_skill(@user.id).id}" %></td>
                <td><%= link_to 'Remove', remove_user_skill_url(skill.user_skill(@user.id).id), :remote => true, method: :delete, data: { confirm: 'Are you sure?' } %></td>

              </tr>
              <script type="text/javascript">
                $(document).on("click", "#update_user_skill_<%= skill.user_skill(@user.id).id %>", function(){
                  $.ajax({
                    url: $(this).attr("href"),
                    complete: function(data){

                      //$(data).appendTo("body");
                      $('#user_skill_<%= skill.user_skill(@user.id).id %>').modal('show');
                    }
                  });
                });
              </script>
            <% end %> 
          </tbody>
        </table>
      <% end %> 
    </div>

    <div class="form-group">
      <div class="col-lg-12">
        <h3>User Projects </h3>
      </div>
    </div>

    <div class="col-lg-12 user-projects">
      <% if ["edit", "update"].include?(params[:action]) && @user.projects.present? %>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th><b>Project Name</b></th>
              <th><b>Description</b></th>
              <th><b>Client Name</b></th>
              <th><b>Actions</b></th>
              </tr>
          </thead>

          <tbody>
            <% @user.projects.each do |project| %>
              <tr id='<%= "user_project_table_row_#{project.id}" %>'>
                <td><%= project.name.titleize %></td>
                <td><%= project.description %></td>
                <td><%= project.client %></td>
                <td><%= link_to 'Remove', remove_user_project_url(project.id), :remote => true, method: :delete, data: { confirm: 'Are you sure?' } %></td>

              </tr>
              
            <% end %> 
          </tbody>
        </table>
      <% end %> 
    </div> 

    <div class="col-lg-12">
      <h4>Add More Skills</h4>
      <div class="skill-container">
        <%= render :partial => 'skill_fields' %>
      </div>
      <hr>
    </div>
    <div class="col-lg-12">
      <h3>Add your project</h3>
      <hr>
      <div class="form-group col-lg-3 projects-select-box">
        <% if @projects.present? %>
      
          <%= select_tag('bio_pic_pages[user_projects]', options_from_collection_for_select(@projects, :id, :name), multiple: true, :class => "form-control skills-section-projects-dropdown") %>
        <% end %>
      </div>
      <div class="form-group col-lg-12">
        <%= link_to "Add new project", "#", :id => "new_project_pane", :remote => true %>
      </div>
    </div>

    <br/>
    <div class="container">
      <div class="form-group col-lg-12">
        <%= submit_tag "Save Changes", :class => "btn btn-primary" %>
      </div>
    </div>  
  <% end %>
</div>
<script type="text/javascript">
  $(document).on("click", "#new_project_pane", function(){
  
    $.ajax({
      url: $(this).attr("href"),
      complete: function(data){

        //$(data).appendTo("body");
        $('#myModal').modal('show');
      }
    });
  });
</script>

app/views/bio_pic_pages/_skill_fields.html.erb
<%#= javascript_tag "var autocomplete_items = #{ @autocomplete_items.to_json };" %>

<div class="skill_div fields form-inline">

  <%= render :partial => "skill_fields_row", :locals => {:skill_form_row_number => "0"} %>
</div>
<br />
<br />
<%= link_to "Add", add_skill_field_form_row_path("1"), :id => 'add_more_skills', :remote => true %>

app/views/bio_pic_pages/_skill_fields_row.html.erb
<br />

<div class="new-skill-field-row-<%= skill_form_row_number %>">
  <div class="form-group">
	  <label>Category</label>
    <%= select_tag("bio_pic_pages[user_skills][#{skill_form_row_number}][category_id]", options_from_collection_for_select(Category.all, :id, :name))%>
  </div>
  
  <div class="form-group">
    <label>Skill</label>
    <%= text_field_tag "bio_pic_pages[user_skills][#{skill_form_row_number}][name]", params[:search], class: "form-control search-query", placeholder: "skill name", type: "search", data: {autocomplete: skills_autocomplete_skill_name_path(:category_id => Category.first.id)} %>
  </div>
  <script type="text/javascript">
    $('#bio_pic_pages_user_skills_<%= skill_form_row_number %>_name').bind('railsAutocomplete.select', function(event, data){
    });
  </script>
  <div class="form-group">
	  <%= radio_button_tag("bio_pic_pages[user_skills][#{skill_form_row_number}][mastered]", true, false, {:class => "radio-inline"}) %>
    <%= label_tag(:mastered, "Mastered") %>
    <%= radio_button_tag("bio_pic_pages[user_skills][#{skill_form_row_number}][mastered]", false, true, {:class => "radio-inline"}) %>
    <%= label_tag(:learning, "Learning") %>
  </div>

  <!-- <div class="form-group">
    
    <%#= select_tag("bio_pic_pages[user_skills][#{skill_form_row_number}][project_id]", options_from_collection_for_select(Project.all, :id, :name), class: "form-control skills-section-projects-dropdown") %>
  </div>

  <div class="form-group">
    <%#= text_field_tag("bio_pic_pages[user_skills][#{skill_form_row_number}][description]", '', :class => "form-control") %>
  </div> -->

	<%= link_to "Remove", "#", :onclick => '$(this).parent().remove();', :remote => true %>
</div>  

app/views/bio_pic_pages/add_skill_field_form_row.js.erb
$('.skill_div').append('<%= j render :partial => "skill_fields_row", :locals => {:skill_form_row_number => "#{@search_field_number}"} %>');
$('#bio_pic_pages_user_skills_<%= (@search_field_number.to_i + 1).to_s %>_name').bind('railsAutocomplete.select', function(event, data){
    });
$("a#add_more_skills").attr("href", "<%= add_skill_field_form_row_path((@search_field_number.to_i + 1).to_s) %>")

app/views/bio_pic_pages/edit.html.erb
<%= render :partial => 'form' %>

app/views/bio_pic_pages/new.html.erb
<%= render :partial => 'form' %>

app/views/bio_pic_pages/show.html.erb
<% provide(:page_title, "#{@user.name.capitalize} | Cyborg SKill Page") %>
<div class="container">
	<!-- Nav tabs -->
	<h1 style = "text-align: center; color:black; font-size: 36px;">User Skill Page</h1>
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active">
			<a href="#basic-info" aria-controls="basic-info" role="tab" data-toggle="tab">Basic Info</a>
		</li>
		<li role="presentation">
			<a href="#skills" aria-controls="skills" role="tab" data-toggle="tab">Skills</a>
		</li>
		<li role="presentation">
			<a href="#projects" aria-controls="projects" role="tab" data-toggle="tab">Projects</a>
		</li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane active" id="basic-info">
			<h2><%= @user.name.titleize %></h2>
            <table class= "table table-striped" id="about-us-institute-table" width="100%" cellspacing="0" cellpadding="0" border="0">
                <tbody>
                    <tr>
                        <td width="20%"><b>Designation</b></td>
                        <td width="80%"><%= @user.designation %></td>
                    </tr>
                    <tr>
                        <td><b>Email Address</b></td>
                        <td><%= @user.email %></td>
                    </tr>
                    <tr>
                        <td><b>Joined On</b></td>
                        <td><%= @user.joined_on %></td>
                    </tr>
                    <tr>
                        <td><b>Education Qualification</b></td>
                        <td><%= @user.education_qualification %></td>
                    </tr>
                </tbody>
            </table>	
		</div>
		<div role="tabpanel" class="tab-pane" id="skills">
			<div class="col-lg-6 col-md-6">

				<h2>Mastered Skills</h2>
				<% if @user_mastered_skills.present? %>
					<table class= "table table-striped table-bordered">
						<tbody>
		                    <% @user_mastered_skills.each do |mastered_skill| %>
			                    <tr>
			                        <td><b><%= link_to mastered_skill.name.titleize, skill_path(mastered_skill) %></b></td>
			                    </tr>
			                <% end %>    
						</tbody>
					</table>
				<% else %>
					<p>User hasn't mastered any skill.</p>
				<% end %>
			</div>
			<div class="col-lg-6 col-md-6">
				<h2>Learning Skills</h2>
				<% if @user_learning_skills.present? %>
					<table class= "table table-striped table-bordered">
						<tbody>
		                    <% @user_learning_skills.each do |learning_skill| %>
			                    <tr>
			                        <td><b><%= link_to learning_skill.name.titleize, skill_path(learning_skill) %></b></td>
			                    </tr>
			                <% end %>
						</tbody>
					</table>
				<% else %>
					<p>User is not learning any skill.</p>
				<% end %>
			</div>
		</div>
		<div role="tabpanel" class="tab-pane" id="projects">
			<h2>User Projects</h2>
			<% if @user.try(:projects).present? %>
				<table class= "table table-striped table-bordered">
					<thead>
						<tr>
		                    <td><b>Project Name</b></td>
		                    <td><b>Description</b></td>
		                    <td><b>Started Since</b></td>
		                    <!-- <td><b>Skills Used in the Project by User</b></td> -->
		                </tr>
		                
					</thead>
					<tbody>
	                    <% @user.try(:projects).try(:each) do |project| %>
		                    
		                    <tr>
		                        <td><%= link_to project.name, project_show_url(project.id) %></td>
		                        <td><%= project.description %></td>
		                        <td><%= project.date_started %></td>
		                        <!-- <td></td> -->
		                    	
		                    </tr>
		                    
		                <% end %>
					</tbody>
				</table>
			<% else %>
				<p>User is not a member of any project.</p>
			<% end %>		
		</div>
	</div>
</div>