config/routes.rb
Rails.application.routes.draw do
  get 'bio_pic_pages/:id/edit', :to => 'bio_pic_pages#edit', :as => :edit_bio_pic_page

  get 'bio_pic_pages/:id/show', :to => 'bio_pic_pages#show', :as => :show_bio_pic_page

  post 'bio_pic_pages/:id/update', :to => 'bio_pic_pages#update', :as => :update_bio_pic_page

  post '/projects/create', :to => 'projects#create', :as => :project_create
  get '/projects', :to => 'projects#index', :as => :projects_index
  get '/projects/:id', :to => 'projects#show', :as => :project_show
  get '/skills', :to => 'skills#index', :as => :skills_index
  delete '/user-skills/:id/remove', :to => 'user_skills#destroy', :as => :remove_user_skill
  delete '/sessions', :to => 'sessions#destroy', :as => :destroy_session
  delete '/users/projects/:id/remove', :to => 'user_projects#remove', :as => :remove_user_project

  get 'skills/autocomplete_skill_name'

  get '/add-skill-field-form-row/:row_number', :to => 'bio_pic_pages#add_skill_field_form_row', :as => :add_skill_field_form_row

  post '/user-skills/:id/update', :to => 'user_skills#update', :as => :update_user_skill
  post '/search/results', :to => 'search#search_results', :as => :search_result
  root 'home#landing'

  resources :users
  resources :projects
  resources :skills do
    collection do
      get :show_by_category
    end
  end

  resources :categories

  get '/auth/google_oauth2/callback', as: "google_oauth", to: 'sessions#create'
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	has_many :user_skills

	has_many :users, :through => :user_skills
	belongs_to :category
	has_and_belongs_to_many :projects
	
	validates :name, :presence => true, :uniqueness => {:case_sensitive => false}

	validates :category_id, presence: true
	#validates :code, presence: true

	accepts_nested_attributes_for :projects

	#CODE_REGEXP = /[A-Z]+[_]*/
	#validates :code, format: { with: CODE_REGEXP }

    #scope :masters, -> includes(:users).where("users.user_skills.where(mastered => true)}

	# before_save :generate_code
	before_save { self.name = name.downcase }

	def generate_code
		#all CAPS and snake case of name attribute
		self.code = name.upcase.gsub(" ", "_")
		#update_attributes(:code => code)
	end

	def user_skill(user_id)
		UserSkill.find_by_user_id_and_skill_id(user_id, self.id)
	end

	def user_with_skill_learning_level(learning_level)
	  user_skills = UserSkill.where(:skill_id => self.id, :mastered => learning_level == "mastered" ? true : false)
	  return User.where(:id => user_skills.flatten.map(&:user_id))
	end

	def self.search(query)
		eager_load(:category).where('skills.name like ?', "%#{query}%")
	end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
	autocomplete :skill, :name, :full => true
	def index 
		@skills = Skill.all
		@hash = @skills.group_by(&:category)
		puts @hash.inspect
	end

	def show
		@skill = Skill.find(params[:id]) 

		respond_to do |format|
			format.js {}
		  format.html { render layout: !request.xhr? }
		end

	end

	def show_by_category
		@skills = Skill.find_by_category_id(params[:category_id])
		render "index"
	end

	def new
		@skill = Skill.new
	end

	def create
		@skill = Skill.new(skill_params)
		if @skill.save
			render "index"
		else
			# puts @skill.errors.messages
			render "new"
		end
	end

	def edit
		@skill = Skill.find(params[:id])
	end

	def update
		@skill = Skill.find(params[:id])
		begin
			@skill.update_attributes!(skill_params)
			redirect_to :action => :show
		rescue ActiveRecord::RecordInvalid => e
			render :edit
		end
	end

	

	def destroy
		@skill = Skill.find(params[:id])
		#skill.delete(@skill.id)
		@skill.destroy
		redirect_to :action => :index
	end

	private 

	def skill_params
		params.require(:skill).permit(:name, :category_id)
	end 

end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_edit_user_skill_modal.html.erb
<div id="user_skill_<%= user_skill_id %>" class="modal fade" style="display:none">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <% user_skill = UserSkill.find(user_skill_id) %>
        <h4>Edit User Skill: <%= user_skill.skill.name.titleize %></h4>
      </div>
      <div style="clear:both;"></div>

      <div class="modal-body" style="height: 140px;">
          <div style="clear:both;"></div>
        
        <p class="form-submit-message"></p>
        <%= form_tag(update_user_skill_path(user_skill_id) , :class => "form-horizontal skill_form", :method => 'post', :remote => true) do %>
          <div class="col-lg-12">
            <div style="clear:both !important;"></div>
            
            <div class="form-group">
              <%= radio_button_tag("bio_pic_pages[user_skills][#{user_skill_id}][mastered]", true, :class => "radio-inline", :checked => user_skill.mastered? ? "checked" : "") %>
              <%= label_tag(:mastered, "Mastered") %>

              <%= radio_button_tag("bio_pic_pages[user_skills][#{user_skill_id}][mastered]", false, {:class => "radio-inline", :checked => !user_skill.mastered? ? "checked" : ""}) %>
              <%= label_tag(:learning, "Learning") %>
            </div>
            <div style="clear:both;"></div>

            <div class="form-group">
              <%#= label_tag("Select Project") %>

              <%#= select_tag("bio_pic_pages[user_skills][#{user_skill_id}][user_projects]", options_from_collection_for_select(@projects, :id, :name), multiple: true, :prompt => 'Select', :class => "form-control skills-section-projects-dropdown") %>
              <br />
              <%= submit_tag "Update User Skill", :class => "btn btn-success" %>
              
            </div>
          </div>  
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" aria-label="Close" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/skills/index.html.erb
<h1 style="text-align:center;color:black;font-size:36px">Skills</h1>
<div class="container" >
  <div class="row" >
    <div class="col-lg-6 col-lg-offset-3">
      <table class="table table-striped table-bordered">
	    <thead>
          <tr>
	        <th>Skill Name</th>
		    <th>Description</th>
          </tr>
	    </thead>
	    <tbody>

          <%# for skill in @skills %>
          <%# binding.pry %>
            <% @hash.each do |category, skills| %>
              <tr><th colspan="2" style="text-align: center"><%= category.name %></th></tr>
            <% for skill in skills %>
              <tr>
  	            <td style="width: 40px"><%= link_to skill.name.titleize, skill_path(skill) %><br/></td>
  	            <td><%= skill.description %></td>
              </tr>  
            <% end %>

            <% end %> 
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/skills/new.html.erb
<%= form_for(@skill) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br/>
<% f.label :category %>
<% f.text_field :category_id %><br/>
<%= f.label :description %>
<%= f.text_field :description %><br/>
<%= f.label :abbreviation %>
<%= f.text_field :abbreviation %><br/>
 <%= f.submit "Add skill" %>
 <% end %>

app/views/skills/show.html.erb
<div class="container">
  <h4><%= @skill.name.titleize %></h4>
  <div><%= @skill.description %></div>
  

  <hr>
  <div class="row">
    <% ["mastered", "learning"].each do |learning_level| %>
      <div class="col-lg-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <span><%= learning_level == "mastered" ? "Masters" : "Learners" %></span>
        </div>
        <div class="panel-body">
          <div class="table-responsive">
            <% instance_variable_set("@#{learning_level}_users", @skill.user_with_skill_learning_level(learning_level))%> 
            <% if instance_variable_get("@#{learning_level}_users").present? %>
              <table class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Designation</th>
                  </tr>
                </thead>
                  <% for user in instance_variable_get("@#{learning_level}_users") %>
                  <%# binding.pry %>
                    <% if user.present? %>
                    <tr>
                      <td><%= link_to user.name.titleize, show_bio_pic_page_path(user) %></td>
                      <td><%= user.email %></td>
                      <td><%= user.designation %></td>
                    </tr>
                    <% end %>
                 <% end %>
              </tbody>
              </table>
            <% else %>
              <p>There are no users who <%= learning_level == "mastered" ? "have mastered" : "are learning" %> this skill.</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<hr>
<div class="row">
  <div class="panel panel-default">
    <div class="panel-heading">
      Projects using <%= @skill.name %>
    </div>
    <div class="panel-body">
      <div class="table-responsive">
        <% if @skill.projects.present? %>
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              <% for project in @skill.projects %>
                <tr>
                  <td><%= link_to project.name.capitalize, project_path(project) %></td>
                  <td><%= project.description %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p>There are no projects which are using this skill</p>
        <% end %>           
      </div>
    </div>
  </div>
</div>