config/routes.rb
Rails.application.routes.draw do
  get 'bio_pic_pages/:id/edit', :to => 'bio_pic_pages#edit', :as => :edit_bio_pic_page

  get 'bio_pic_pages/:id/show', :to => 'bio_pic_pages#show', :as => :show_bio_pic_page

  post 'bio_pic_pages/:id/update', :to => 'bio_pic_pages#update', :as => :update_bio_pic_page

  post '/projects/create', :to => 'projects#create', :as => :project_create
  get '/projects', :to => 'projects#index', :as => :projects_index
  get '/projects/:id', :to => 'projects#show', :as => :project_show
  get '/skills', :to => 'skills#index', :as => :skills_index
  delete '/user-skills/:id/remove', :to => 'user_skills#destroy', :as => :remove_user_skill
  delete '/sessions', :to => 'sessions#destroy', :as => :destroy_session
  delete '/users/projects/:id/remove', :to => 'user_projects#remove', :as => :remove_user_project

  get 'skills/autocomplete_skill_name'

  get '/add-skill-field-form-row/:row_number', :to => 'bio_pic_pages#add_skill_field_form_row', :as => :add_skill_field_form_row

  post '/user-skills/:id/update', :to => 'user_skills#update', :as => :update_user_skill
  post '/search/results', :to => 'search#search_results', :as => :search_result
  root 'home#landing'

  resources :users
  resources :projects
  resources :skills do
    collection do
      get :show_by_category
    end
  end

  resources :categories

  get '/auth/google_oauth2/callback', as: "google_oauth", to: 'sessions#create'
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_and_belongs_to_many :skills
	has_and_belongs_to_many :users
	validates :name, :presence => true, :uniqueness => {:case_sensitive => false}
	validates :description, :presence => true

	scope :all_except, ->(projects) { where.not(id: projects)}

  before_save {self.name = name.downcase}

  def self.search(query)
    where("name like ?", "%#{query}%")
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index 
		@projects = Project.all
		
	end

	def show
		@project = Project.find(params[:id])

	end

	def create
		@projects = Project.all_except(current_user.projects)
		@project = Project.new(project_params)
		@project.save
		respond_to do |format|
			format.js
		end 
	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])
		begin
			@project.update_attributes!(project_params)
			redirect_to :action => :show
		rescue ActiveRecord::RecordInvalid => e
			render :edit
		end
	end

	def destroy
		@project = Project.find(params[:id])
		#project.delete(@project.id)
		@project.destroy
		redirect_to :action => :index
	end

	private 

	def project_params
		params.require(:project).permit(:name, :description, :client, :date_started)
	end 
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form_modal.html.erb
<div id="myModal" class="modal fade" style="display:none">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Add New Project</h4>
      </div>
      <div class="modal-body">
        <p class="form-submit-message"></p>
        <%= form_for :project, :url => project_create_path ,:html => {:class => "form-horizontal skill_form", :method => 'post', :remote => true}  do |f| %>
          <%= f.label "Name"%>
          <%= f.text_field :name, :class => "form-control", :style => "margin-bottom: 10px;" %>
          <%= f.label "Description" %>
          <%= f.text_field :description, :class => "form-control", :style => "margin-bottom: 10px;" %>
          <%= f.label "Client" %>
          <%= f.text_field :client, :class => "form-control", :style => "margin-bottom: 20px;" %>
          <%= f.label "Date started" %>
          <%= f.text_field :date_started, :style => "margin-bottom: 10px;" %><br/>
          <%= f.submit "Add Project", :class => "btn btn-success" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" aria-label="Close" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/projects/create.js.erb
$(document).ready(function(){
	<% if @project.id.present? %>
		$('.skills-section-projects-dropdown').html("<% @projects.each do |project| %><option value = '<%= project.id %>'><%= project.name %></option><% end %>");
		$('.projects-select-box').html('<%= j select_tag("bio_pic_pages[user_projects]", options_from_collection_for_select(@projects, :id, :name), multiple: true, :class => "form-control skills-section-projects-dropdown") %>');
		$('.form-submit-message').html('Project successfully created');
	<% else %>
		$('.form-submit-message').html('Project creation failed<ul><%@project.errors.full_messages.each do |full_message|%><li><%= full_message %></li><% end %></ul>');
	<% end %>	
		
});

app/views/projects/index.html.erb
<% provide(:page_title, "Projects") %>
<h1 style = "text-align: center; color:black; font-size: 36px;">Listing Projects</h1>
<div class="container">
	<table class="table table-bordered">
		<thead>
			<tr>
		        <td><b>Project Name</b></td>
		        <td><b>Description</b></td>
		        <td><b>Started Since</b></td>
		        <td><b>Client Name</b></td>
		    </tr>
		</thead>

		<tbody>
			<% @projects.each do |project| %>
	  			<tr>
		            <td><%= link_to project.name.titleize, project_show_url(project.id) %></td>
		            <td><%= project.description %></td>
		            <td><%= project.date_started %></td>
		            <td><%= project.client %></td>

		        </tr>
		    <% end %>	
		</tbody>
	</table>
</div>

app/views/projects/show.html.erb
<% provide(:page_title, "#{@project.name} | Projects") %>

<div class="container">
	<h1 style = "text-align: center; color:black; font-size: 48px;"><%= @project.name.capitalize %></h1>
	
	<h3>Basic Info</h3>
    <table class= "table table-striped" id="about-us-institute-table" width="100%" cellspacing="0" cellpadding="0" border="0">
        <tbody>
            <tr>
                <td width="20%"><b>Description</b></td>
                <td width="80%"><%= @project.description %></td>
            </tr>
            <tr>
                <td><b>Client Name</b></td>
                <td><%= @project.client %></td>
            </tr>
            <tr>
                <td><b>Project Started Since</b></td>
                <td><%= @project.date_started %></td>
            </tr>
            
        </tbody>
    </table>

	<h3>Skills Used in the Project</h3>
    <% if @project.skills.present? %>
        <table class= "table table-striped table-bordered">
    		<thead>
    			<tr>
    				<td><b>Skill Name</b></td>
    				<td><b>Description</b></td>
    				<td><b>Skill Category</b></td>
    			</tr>
    		</thead>
    		<tbody>
                <% @project.skills.each do |skill| %>
                    <tr>
                        <td><%= link_to skill.name.titleize, skill_path(skill) %></td>
                    	<td><%= skill.description %></td>
                    	<td><%= skill.category.name %></td>
                    </tr>
                <% end %>    
    		</tbody>
    	</table>
    <% else %>
        <p>There are no skills used in the project.</p>
    <% end %>        

	<hr>
	<h3>Members in the Project</h3>
    <% if @project.users.present? %>	
        <table class= "table table-striped table-bordered">
    		<thead>
    			<tr>
    				<td><b>Name</b></td>
    				<td><b>Email</b></td>
    				<td><b>Designation</b></td>
    				<td><b>Educational Qualification</b></td>
    			</tr>
    		</thead>
    		<tbody>
                <% @project.users.each do |user| %>
                    <tr>
                        <td><%= link_to user.name.titleize, show_bio_pic_page_path(user.id) %></td>
                    	<td><%= user.email %></td>
                    	<td><%= user.designation %></td>
                    	<td><%= user.education_qualification %></td>
                    </tr>
                <% end %>    
    		</tbody>
    	</table>
    <% else %>
        <p>There are no members in the project.</p>
    <% end %>    
</div>