config/routes.rb
Rails.application.routes.draw do
  get 'bio_pic_pages/:id/edit', :to => 'bio_pic_pages#edit', :as => :edit_bio_pic_page

  get 'bio_pic_pages/:id/show', :to => 'bio_pic_pages#show', :as => :show_bio_pic_page

  post 'bio_pic_pages/:id/update', :to => 'bio_pic_pages#update', :as => :update_bio_pic_page

  post '/projects/create', :to => 'projects#create', :as => :project_create
  get '/projects', :to => 'projects#index', :as => :projects_index
  get '/projects/:id', :to => 'projects#show', :as => :project_show
  get '/skills', :to => 'skills#index', :as => :skills_index
  delete '/user-skills/:id/remove', :to => 'user_skills#destroy', :as => :remove_user_skill
  delete '/sessions', :to => 'sessions#destroy', :as => :destroy_session
  delete '/users/projects/:id/remove', :to => 'user_projects#remove', :as => :remove_user_project

  get 'skills/autocomplete_skill_name'

  get '/add-skill-field-form-row/:row_number', :to => 'bio_pic_pages#add_skill_field_form_row', :as => :add_skill_field_form_row

  post '/user-skills/:id/update', :to => 'user_skills#update', :as => :update_user_skill
  post '/search/results', :to => 'search#search_results', :as => :search_result
  root 'home#landing'

  resources :users
  resources :projects
  resources :skills do
    collection do
      get :show_by_category
    end
  end

  resources :categories

  get '/auth/google_oauth2/callback', as: "google_oauth", to: 'sessions#create'
end

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer" style = "border-top: 1px solid #E5E5E5;">
		<p style="margin-top:10px;">© <%= link_to 'Cybrilla Technologies', 'http://www.cybrilla.com' %> 2015</p>
	</footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Cyborg Skills Profile</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li><a href="/users">Users</a></li>
            <li><a href="/categories">Categories</a></li>
            <li><a href="/skills">Skills</a></li>
            <li><a href="/projects">Projects</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= form_tag search_result_path do %>
                <input type="text" id="search" name = "header_search" placeholder="Search..." />
                <!-- <button class="btn" type="submit"<i class="icon-search"></i></button> -->
              <% end %>
            </li>
            <li class="dropdown pull-right">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href=<%= show_bio_pic_page_path(current_user) %>>My Profile</a></li>
                <li><a href=<%= edit_bio_pic_page_path(current_user) %>>Edit Profile</a></li>
                <li role="separator" class="divider"></li>
                <li><a href=<%= destroy_session_path %> data-method="delete">Sign Out</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= raw(full_title(yield(:page_title))) %></title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
   <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if signed_in? %>
	  <%= render :partial => "layouts/header" %>
	<% end %>
  <div class="container">
    <% if notice && params[:action] != "landing" %>
      <div class= "alert alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>
  </div>
  <%= yield %>

  <%= render :partial => "layouts/footer" %>

</body>
</html>